import 'package:flutter/material.dart';
import 'package:flutter_application_1/screens/new_tax_invoice.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

class TaxInvoiceScreen extends StatefulWidget {
  @override
  _TaxInvoiceScreenState createState() => _TaxInvoiceScreenState();
}

class _TaxInvoiceScreenState extends State<TaxInvoiceScreen> {
  String paymentMode = 'Credit';
  String customer = 'Brutal Clothing';
  String shippingAddress = 'Store Address';
  DateTime? paymentDueDate;
  String placeOfSupply = '';


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () {
            Navigator.pushReplacement(
          context,
          MaterialPageRoute(
            builder: (context) => NewTaxInvoiceScreen()
          ),
        );
          },
        ),
        title: const Text('Tax Invoice'),
        actions: [
          IconButton(
            icon: const Icon(Icons.picture_as_pdf),
            onPressed: () {},
          ),
        ],
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
               const Row(
              children: [
                Text('Customer: ', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
                Text('Brutal Clothing', style: TextStyle(fontWeight: FontWeight.bold)),
              ],
            ),

            const Row(
              children: [
                Text('GST: ', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
                Text('QYHDGBAK3457', style: TextStyle(fontWeight: FontWeight.bold)),
              ],
            ),

             const Row(
              children: [
                Text('DDMMYY 13:45PM', style: TextStyle(color: Colors.blue)),
              ],
            ),

            const Row(
              children: [
                Text('Generated by: ', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
                Text('Sunil', style: TextStyle(fontWeight: FontWeight.bold)),
              ],
            ),

            const Row(
              children: [
                const Text('Purchased Order No.: ', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
                const Text('84692', style: TextStyle(fontWeight: FontWeight.bold)),
              ],
            ),

            const Row(
              children: [
                const Text('Invoice No.: ', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
                const Text('78541', style: TextStyle(fontWeight: FontWeight.bold)),
              ],
            ),
                 
              const SizedBox(height: 20),
              buildProductCard(),
              const SizedBox(height: 20),
              buildCustomerDetailsSection(),
              const SizedBox(height: 20),
              buildPaymentSummarySection(),
              const SizedBox(height: 20),
              buildGenerateTaxInvoiceButton(),
            ],
          ),
        ),
      ),
    );
  }

Widget buildProductCard() {
    return Card(
      color: Colors.white,
      elevation: 2,
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Item Details'),
            buildProductTile('Leather Bag'),
            buildProductTile('Walking Shoes'),
            buildProductTile('Pink Bag'),
          ],
        ),
      ),
    );
  }

  ListTile buildProductTile(String productName) {
    return ListTile(
      leading: Image.network('https://via.placeholder.com/150'),
      title: Text(productName),
      subtitle: const Text(
          'Women\'s Accessories | 35 Pieces\nHSN CODE: 12DHRY334RF'),
      trailing: const Text('₹1,200'),
    );
  }
  Widget buildCustomerDetailsSection() {
    return Card(
      color: Colors.white,
      elevation: 2,
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                const Text('Customer Details',
                    style: TextStyle(fontWeight: FontWeight.bold)),
                TextButton(
                  onPressed: () {
                    // Add new customer logic here
                  },
                  child: const Text('+ Add New'),
                ),
              ],
            ),
            TextField(
              decoration: InputDecoration(
                hintText: 'Enter Customer Details',
                border: const OutlineInputBorder(
                  borderSide: BorderSide(
                    style: BorderStyle.none,
                  ),
                ),
                suffixIcon: IconButton(
                  icon: const Icon(Icons.close),
                  onPressed: () {
                    setState(() {
                      customer = '';
                    });
                  },
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget buildPaymentSummarySection() {
    return const Card(
      color: Colors.white,
      elevation: 2,
      child: Padding(
        padding: EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Payment Summary', style: TextStyle(fontWeight: FontWeight.bold)),
            SizedBox(height: 10),
            Row(
              children: [
                Text('Item Total', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
                Spacer(),
                Text('Rs 3,600', style: TextStyle(color: Colors.black)),
              ],
            ),
            Row(
              children: [
                Text('Total Taxable Amount12%', style: TextStyle(color: Colors.grey, fontWeight: FontWeight.bold)),
                Spacer(),
                Text('Rs 600'),
              ],
            ),
            Row(
              children: [
                Text('Other Changes', style: TextStyle(color: Colors.grey)),
                Spacer(),
                Text('Rs 0', style: TextStyle(color: Colors.grey)),
              ],
            ),
            Row(
              children: [
                Text('Total Discount', style: TextStyle(color: Colors.lightGreen,decoration: TextDecoration.underline,decorationColor: Colors.lightGreen,)),
                Spacer(),
                Text('-Rs 200', style: TextStyle(color: Colors.lightGreen)),
              ],
            ),
            SizedBox(height: 20,),
             Row(
              children: [
                Text('Bank A/C Number', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
                Spacer(),
                Text('123456789', style: TextStyle(color: Colors.black)),
              ],
            ),
            Row(
              children: [
                Text('Bank Name', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
                Spacer(),
                Text('Kotak Mahindra Bank'),
              ],
            ),
            Row(
              children: [
                Text('IFSC', style: TextStyle(color: Colors.grey)),
                Spacer(),
                Text('ABCD1234', style: TextStyle(color: Colors.grey)),
              ],
            ),
            Row(
              children: [
                Text('Swift Code', style: TextStyle(color: Colors.grey)),
                Spacer(),
                Text('123456789', style: TextStyle(color: Colors.grey)),
              ],
            ),
            SizedBox(height: 20,),
             const Row(
              children: [
                Text('Payment Method', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold,decoration: TextDecoration.underline,)),
                Spacer(),
                Text('Card', style: TextStyle(fontWeight: FontWeight.bold)),
              ],
            ),
            SizedBox(height: 20,),
             const Row(
              children: [
                Text('Expecting Delivery by', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold,decoration: TextDecoration.underline,)),
                Spacer(),
                Text('DDMMYY', style: TextStyle(fontWeight: FontWeight.bold)),
              ],
            ),
            Divider(
              color: Colors.blue,
              thickness: 1,
              height: 20,
              endIndent: 0,
              indent: 0,
            ),
            Row(
              children: [
                Text('Total Amount Payable', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
                Spacer(),
                Text('Rs 4,000', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
              ],
            ),
          ],
        ),
      ),
    );
  }


  Widget buildGenerateTaxInvoiceButton() {
    return Padding(
      padding: const EdgeInsets.all(18.0),
      child: ElevatedButton(
        onPressed: () {
          
        },
        child: const Text(
          'Convert to Delivery Challan',
          style: TextStyle(color: Colors.white, fontSize: 18),
        ),
        style: ElevatedButton.styleFrom(
          minimumSize: const Size(double.infinity, 45),
          backgroundColor: const Color(0xFF1570EF),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
            side: const BorderSide(color: Colors.blue),
          ),
        ),
      ),
    );
  }
}
